config/routes.rb
Rails.application.routes.draw do
  root 'quantities#index'
  get '/login', to: 'pag_estatica#login'
  get '/show', to: 'pag_estatica#show'
  get '/libManager', to: 'books#index'
  get '/libPlus', to: 'books#new'
  get '/tiendaManager', to: 'tiendas#index'
  get '/tiendaPlus', to: 'tiendas#new'
  get '/createRelation', to: 'quantities#new'
  resources :tiendas
  resources :books
  resources :quantities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :quantities, foreign_key: "tienda_id", dependent: :destroy
  has_many :tiendas, through:  :quantities
  validates :title, presence: true
  validates :author, presence: true
  validates :year, presence: true
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :tienda, class_name: "Tienda"
  belongs_to :book, class_name: "Book"
  validates :tienda_id, presence: true
  validates :book_id, presence: true
  validates :quantity, presence: true
  
  def self.search(search)
    collection = joins(:book, :tienda)
    return collection unless search
    
    collection.where(tiendas: { codename: search })
      .or(collection.where(books: { title: search }))
      .or(collection.where(books: { author: search}))
      .or(collection.where(books: { year: search}))
  end
end

app/models/tienda.rb
class Tienda < ApplicationRecord
  has_many :quantities, foreign_key: "book_id", dependent: :destroy
  has_many :books, through: :quantities
  validates :codename, presence: true, uniqueness: true
  validates :address, presence: true
  validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def show
    @book = Book.find(params[:id])
    @quantities = @book.quantities.paginate(page: params[:page])
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:sucess] = "Libro agregado"
      redirect_to @book
    else
      render 'new'
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "Datos actualizados"
      redirect_to libManager_path
    else
      render 'edit'
    end
  end
    
  def index
    @books = Book.all
  end
  
  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Libro eliminado"
    redirect_to books_url
  end
  
  private
  
    def book_params
      params.require(:book).permit(:title, :author, :year)
    end
  
end

app/controllers/pag_estatica_controller.rb
class PagEstaticaController < ApplicationController
  def login
  end

  def home
  end

  def show
  end

  def libManager
  end

  def tiendaManager
  end
  
  def libPlus
  end

end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController
  def new
    @quantity = Quantity.new
  end
  
  def create
    @quantity = Quantity.create(quantity_params)
    if @quantity.save
      flash[:success] = "Relacion creada"
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def destroy
    Quantity.find(params[:id]).destroy
    flash[:success] = "Relacion destruida"
    redirect_to root_path
  end
  
  def edit
    @quantity = Quantity.find(params[:id])
  end
  
  def update
    @quantity = Quantity.find(params[:id])
    if @quantity.update(quantity_params)
      flash[:success] = "Datos actualizados"
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
  def index
    @quantities = Quantity.search(params[:search])
  end
  
  private
    def quantity_params
      params.require(:quantity).permit(:book_id, :tienda_id, :quantity, :search)
    end
end

app/controllers/tiendas_controller.rb
class TiendasController < ApplicationController
  
  def show
    @tienda = Tienda.find(params[:id])
    @inventories = @tienda.quantities.paginate(page: params[:page])
  end
  
  def new
    @tienda = Tienda.new
  end
  
  def create
    @tienda = Tienda.new(tienda_params)
    if @tienda.save
      flash[:sucess] = "Tienda agregada"
      redirect_to @tienda
    else
      render 'new'
    end
  end
  
  def edit
    @tienda = Tienda.find(params[:id])
  end
  
  def update
    @tienda = Tienda.find(params[:id])
    if @tienda.update(tienda_params)
      flash[:success] = "Datos actualizados"
      redirect_to @tienda
    else
      render 'edit'
    end
  end
    
  def index
    @tiendas = Tienda.all
  end
  
  def destroy
    Tienda.find(params[:id]).destroy
    flash[:success] = "Tienda eliminada"
    redirect_to tiendas_url
  end
  
  private
  
    def tienda_params
      params.require(:tienda).permit(:codename, :address, :phone)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pag_estatica_helper.rb
module PagEstaticaHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/helpers/tiendas_helper.rb
module TiendasHelper
end

app/views/books/_form.html.slim
= form_with(model: @book, local: true) do |f|
      = f.label :title
      = f.text_field :title, class: 'form-control'
      
      = f.label :author
      = f.text_field :author, class: 'form-control'
      
      = f.label :year
      = f.number_field :year, class: 'form-control'
      
      = f.submit "Guardar cambios", class: "btn btn-primary"

app/views/books/edit.html.slim
- provide(:title, 'Editar libro')
- provide(:button_text, 'Guardar cambios')
h1 Editar Libro
.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/books/index.html.slim
- provide(:title, 'Libros manager')
h1 Todos los libros
= link_to "Agregar libro", libPlus_path, class: "btn btn-lg btn-primary"

br/

table.blueTable
  tbody  
  - @books.each do |book|
    tr
      td
        = link_to book.title, book
      td
        = link_to "Editar information", edit_book_path(book)
      td
        = link_to "Borrar libro", book, method: :delete, data: { confirm: "You sure?" }

app/views/books/new.html.slim
- provide(:title, 'Agregar Libro')
- provide(:button_text, 'Agregar Libro')
h1 Agregar Libro
.row
  .col-md-6.col-md-offset-3
      = render 'form'

app/views/books/show.html.slim
- provide(:title, @book.title)

.row
  aside.col-md-4
    section.book_info
      h1
        = @book.title
      h2
        = @book.author 
        
        = @book.year
  .col-md-8
    h3 Inventario en tiendas
    - if @book.quantities.any?
      table.blueTable
        tbody
          - @quantities.each do |quantity|
            tr
              td.tienda= link_to quantity.tienda.codename, tienda_path(quantity.tienda)
              td.tienda= quantity.tienda.address
              td.quantity
                = quantity.quantity
    = will_paginate @quantities
      

app/views/layouts/_footer.html.slim
footer.footer
  small
    | This is my proyect sample for UKKO.

app/views/layouts/_header.html.slim
body
  header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "libreria ejemplo", root_path, id: "logo"
      nav
        ul.nav.navbar-nav.navbar-right
          li= link_to "Home", root_path
          li= link_to "Libros Manager", libManager_path
          li= link_to "Tiendas Manager", tiendaManager_path

app/views/layouts/_rails_default.html.slim
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'          
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title
      = yield(:title)
      | | Libreria Ejemplo %&gt;
    = render 'layouts/rails_default'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        div class=("alert alert-#{message_type}") = message
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development? 

app/views/pag_estatica/home.html.slim
.center.jumbotron
  h1 Libreria Ejemplo
  h2
    | Busca de acuerdo a tu preferencia
    
= render 'quantities/index'

app/views/pag_estatica/login.html.slim
- provide(:title, "Log in")
doctype html
html

  body
    h1 Log in
    p Proporciona tu usuario y contraseña

app/views/pag_estatica/show.html.slim
- provide(:title, "Show")
doctype html
html

  body
    h1 Libreria Ejemplo

app/views/quantities/_form.html.slim
= form_with(model: @quantity, local: true, method: "post") do |f|
      = f.label :tienda_id
      select name="quantity[tienda_id]"
        option value=""  Seleccione una tienda
        - Tienda.all.each do |tienda|
          option value="#{tienda.id}" = tienda.codename
      
      = f.label :book_id
      select name="quantity[book_id]"
        option value=""  Seleccione un libro
        - Book.all.each do |book|
          option value="#{book.id}" = book.title
      
      = f.label :quantity
      = f.number_field :quantity, class: 'form-control'
      
      = f.submit "Crear relacion", class: "btn btn-primary"

app/views/quantities/_formE.html.slim
= form_with(model: @quantity, local: true) do |f|
      
      = f.label :quantity
      = f.number_field :quantity, class: 'form-control'
      
      = f.submit "Crear relacion", class: "btn btn-primary"

app/views/quantities/_inventory.slim
table.blueTable
  tbody
    tr
      td.tienda= link_to Book.find_by(id: quantity.book_id).title, Book.find_by(id: quantity.book_id)
      td.tienda= Book.find_by(id: quantity.book_id).author
      td.quantity
        = quantity.quantity

app/views/quantities/_quantity.html.slim
table.blueTable
  tbody
    tr
      td.tienda= link_to Tienda.find_by(id: quantity.tienda_id).codename, Tienda.find_by(id: quantity.tienda_id)
      td.tienda= Tienda.find_by(id: quantity.tienda_id).address
      td.quantity
        = quantity.quantity

app/views/quantities/edit.html.slim
- provide(:title, 'Editar relacion')
- provide(:button_text, 'Guardar Cambios')
h1 Editar relación
.row
  .col-md-6.col-md-offset-3
      = render 'formE'

app/views/quantities/index.html.slim
.center.jumbotron
  h1 Libreria Ejemplo
  h2
    | Busca de acuerdo a tu preferencia
  = link_to "Crear Relacion", createRelation_path, class: "btn btn-lg btn-primary"  
    

h4 Buscar:
= form_tag(quantities_path, method: :get) do
  = text_field_tag(:search, params[:search])
  = submit_tag("Search")

      
table.blueTable
  thead
    tr
      th Tienda
      th Libro
      th Autor
      th Year
      th Cantidad
  tbody
    - @quantities.each do |quantity|
      tr
        td
          = quantity.tienda.codename
        td
          = quantity.book.title
        td
          = quantity.book.author
        td
          = quantity.book.year
        td
          = link_to quantity.quantity, edit_quantity_path(quantity)  
        td
          = link_to "Borrar libros de la tienda", quantity, method: :delete, data: { confirm: "You sure?" }

app/views/quantities/new.html.slim
- provide(:title, 'Nueva relacion')
- provide(:button_text, 'Crear Relacion')
h1 Crear relacion
.row
  .col-md-6.col-md-offset-3
      = render 'form'

app/views/tiendas/_form.html.slim
= form_with(model: @tienda, local: true) do |f|
      = f.label :codename
      = f.text_field :codename, class: 'form-control'
      
      = f.label :address
      = f.text_field :address, class: 'form-control'
      
      = f.label :phone
      = f.text_field :phone, class: 'form-control'
      
      = f.submit "Guardar cambios", class: "btn btn-primary"

app/views/tiendas/edit.html.slim
- provide(:title, 'Editar tienda')
- provide(:button_text, 'Guardar cambios')
h1 Editar Tienda
.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/tiendas/index.html.slim
- provide(:title, 'Tienda manager')
h1 Todas las tiendas
= link_to "Agregar tienda", tiendaPlus_path, class: "btn btn-lg btn-primary"

table.blueTable
  tbody  
  - @tiendas.each do |tienda|
    tr
      td
        = link_to tienda.codename, tienda
      td
        = link_to "Editar information", edit_tienda_path(tienda)
      td
        = link_to "Borrar tienda", tienda, method: :delete, data: { confirm: "You sure?" }

app/views/tiendas/new.html.slim
- provide(:title, 'Agregar Tienda')
- provide(:button_text, 'Agregar Tienda')
h1 Agregar Tienda
.row
  .col-md-6.col-md-offset-3
      = render 'form'

app/views/tiendas/show.html.slim
- provide(:title, @tienda.codename)
.row
  aside.col-md-4
    section.book_info
      h1
        = @tienda.codename
      h2
        = @tienda.address
        = @tienda.phone
  .col-md-8
    h3 Libros en la tienda
    - if @inventories.any?
      table.blueTable
        tbody
          - @inventories.each do |quantity|
            tr
              td.tienda= link_to quantity.book.title, book_path(quantity.book)
              td.tienda= quantity.book.author
              td.quantity
                = quantity.quantity
    = will_paginate @inventories
      